sudo: required 
services:
  - docker
before_install: 
  - docker build -t 1383/nodejs:travis  -f Dockerfile.dev .
script:
  - docker run 1383/nodejs:travis npm run test -- --coverage
deploy:
  provider: elasticbeanstalk 
  region: "us-east-1"
  app: "test_docker"
  env: "TestDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-400446100037"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $access_key_id
  secret_access_key: $secret_access_key
